inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Style/StringLiterals:
  EnforcedStyle: double_quotes
